# render.yaml

services:
  - name: repayment-marking
    env: production
    startCommand: python app.py  
    routes:
      - src: /
        dest: repayment-marking  # This should match the 'name' of your service
    buildCommand: pip install -r requirements.txt

