# render.yaml

services:
  - name: repayment-marking
    env: production
    startCommand: gunicorn app:app  --port 5000
    healthCheckPath: /
    routes:
      - src: /
        dest: repayment-marking  # This should match the 'name' of your service
    buildCommand: pip install -r requirements.txt

